// ============================================================================
// collectina — Database types (single source of truth: scripts/schema.sql)
// ============================================================================
// These are hand-written domain types matching the production schema exactly.
// They are NOT generated by Supabase — they mirror scripts/schema.sql.
//
// Updated 2026-08-18 to include all columns, correct types, and correct
// nullability as verified against production via the service_role key.
// ============================================================================

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export type DiscountType = "percentage" | "fixed" | "free_shipping";

export type OrderStatus =
  | "pending"
  | "paid"
  | "outofstock"
  | "processing"
  | "ready"
  | "delivered"
  | "returned"
  | "canceled"
  | "refunded";

// ---------------------------------------------------------------------------
// Domain types
// ---------------------------------------------------------------------------

/**
 * profiles — one row per user. FK id → auth.users ON DELETE CASCADE.
 * display_name is nullable (the trigger doesn't set it).
 */
export interface Profile {
  id: string;
  display_name: string | null;
  phone_number: string | null;
  address: string | null;
  city: string | null;
  postal_code: string | null;
  telegram: string | null;
  beta_og: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * products — design images. type is 'phonecase' | 'poster' (nullable text).
 * feed/pin control homepage visibility. designer FK → auth.users (nullable FK).
 */
export interface Product {
  id: string;
  name: string | null;
  description: string | null;
  image_url: string | null;
  designer: string | null;
  feed: boolean;
  pin: boolean;
  type: "phonecase" | "poster" | null;
  created_at: string;
  updated_at: string;
}

/**
 * phone_cases — variant pricing for phone case products.
 * unique(brand, model). price is numeric(10,2).
 */
export interface PhoneCase {
  id: string;
  brand: string;
  model: string;
  price: number;
  available: boolean;
  created_at: string;
  updated_at: string;
}

/**
 * posters — variant pricing for poster products.
 * ⚠️ price is TEXT (stores "50000" etc.) — not a number. This is a verified
 * production quirk. no updated_at column.
 */
export interface Poster {
  id: string;
  attribute: string | null;
  price: string;
  created_at: string;
  available: boolean;
}

/**
 * cart_items — per-user shopping cart. FKs user_id, product_id (CASCADE),
 * phone_case_id (CASCADE), poster_id (SET NULL).
 * unique(user_id, product_id, phone_case_id).
 */
export interface CartItem {
  id: string;
  user_id: string;
  product_id: string;
  quantity: number;
  created_at: string;
  updated_at: string;
  phone_case_id: string | null;
  poster_id: string | null;
}

/**
 * orders — one per purchase. total_amount numeric(10,2), status text.
 * track_id is int4 NOT NULL UNIQUE (generated via generate_track_id()).
 * payment_reference stores the Zibal trackId.
 */
export interface Order {
  id: string;
  user_id: string;
  total_amount: number;
  status: string;
  payment_reference: string | null;
  shipping_address: string;
  shipping_city: string;
  shipping_postal_code: string;
  phone_number: string;
  telegram: string | null;
  receiver_name: string | null;
  track_id: number;
  track_post_id: string | null;
  discount_id: string | null;
  discount_amount: number;
  free_shipping: boolean;
  note: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * order_items — line items within an order. product_price numeric(10,2).
 * FKs: order_id (CASCADE), product_id (no action), phone_case_id (no action),
 * poster_id (SET NULL).
 */
export interface OrderItem {
  id: string;
  order_id: string;
  product_id: string;
  product_name: string;
  product_price: number;
  quantity: number;
  created_at: string;
  phone_case_id: string | null;
  phone_brand: string | null;
  phone_model: string | null;
  poster_atr: string | null;
  poster_id: string | null;
}

/**
 * discounts — promo codes. type is the discount_type enum.
 * All money columns are plain numeric (not numeric(10,2)).
 * No updated_at column.
 */
export interface Discount {
  id: string;
  code: string;
  type: DiscountType;
  value: number | null;
  max_discount_amount: number | null;
  min_order_amount: number | null;
  starts_at: string | null;
  expires_at: string | null;
  usage_limit: number | null;
  usage_per_user: number | null;
  is_active: boolean;
  created_at: string;
}

/**
 * discount_usages — tracks which user used which discount on which order.
 * unique(discount_id, user_id) and unique(discount_id, order_id).
 */
export interface DiscountUsage {
  id: string;
  discount_id: string;
  user_id: string;
  order_id: string;
  used_at: string;
}

/**
 * discount_usage_stats — VIEW (discount_id, total_usage bigint).
 */
export interface DiscountUsageStats {
  discount_id: string;
  total_usage: number;
}

/**
 * settings — single-row app config. bigint id via identity.
 * post_price is plain numeric. No timestamps.
 */
export interface Settings {
  id: number;
  post_price: number;
  top_banner: string | null;
  show_phonecase: boolean;
  show_poster: boolean;
}

// ---------------------------------------------------------------------------
// Composite / join types (used by queries that nest related data)
// ---------------------------------------------------------------------------

/** Cart item with joined product + variant data (used by cart page). */
export interface CartItemWithDetails extends CartItem {
  product: Product;
  phone_case: PhoneCase | null;
  poster: Poster | null;
}

/** Order with nested order_items (used by admin, track page). */
export interface OrderWithItems extends Order {
  order_items: OrderItem[];
}

/** Product with nested variant list (used by product detail pages). */
export interface ProductWithVariants extends Product {
  phone_cases?: PhoneCase[];
  posters?: Poster[];
}